"""Importer tests: AutoEQ, REW, EqualizerAPO, CSV, detection."""
from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from eqforge.importers import autoeq, detect, equalizerapo, rew

AUTOEQ_SAMPLE = textwrap.dedent("""\
    # Generated by AutoEQ
    Preamp: -6.2 dB
    Filter 1: ON PK       Fc    105.0 Hz Gain  5.10 dB Q 1.100
    Filter 2: ON PK       Fc    2100 Hz Gain -3.20 dB Q 2.500
    Filter 3: ON LSC      Fc     30.0 Hz Gain  2.00 dB Q 0.700
    Filter 4: OFF HSC     Fc   9000.0 Hz Gain -1.00 dB Q 0.700
    Filter 5: ON HPF      Fc     20.0 Hz Q 0.707
""")

REW_SAMPLE = textwrap.dedent("""\
    * EQ Dump saved by REW
    Filter  1: ON  PK       Fc    105.0 Hz Gain  +5.1 dB Q 1.100
    Filter  2: ON  Peak     Fc   3000.0 Hz Gain  -2.5 dB BW 1.5 oct
    Filter  3: ON  LSC      Fc     30.0 Hz Gain  +3.0 dB Q 0.707
""")

APO_SAMPLE = textwrap.dedent("""\
    # Equalizer APO config
    Preamp: -3 dB
    Filter: ON PK Fc 1000 Hz Gain -4.5 dB Q 2.0
    GraphicEQ: 25 -1.5; 40 0.0; 63 2.1; 160 -0.8; 400 0.5; 1000 0.0; 2500 1.2; 6300 -1.0; 16000 0.8
    Device: USB DAC XYZ;
    Include: extra.txt
""")

CSV_SAMPLE = "freq,gain,q,type\n100,3.5,1.0,peak\n8000,-2,0.7,highshelf\n"


def test_autoeq_parse():
    r = autoeq.parse_autoeq(AUTOEQ_SAMPLE)
    assert r["preamp_db"] == pytest.approx(-6.2)
    assert len(r["filters"]) == 5
    f1 = r["filters"][0]
    assert (f1["type"], f1["freq"], f1["gain_db"], f1["q"]) == \
        ("peak", 105.0, 5.1, 1.1)
    assert r["filters"][2]["type"] == "lowshelf"
    assert r["filters"][3]["enabled"] is False
    assert r["filters"][4]["type"] == "highpass"


def test_autoeq_csv_variant():
    text = "Filter,Frequency,Quality,Gain\n1 ON PK,105,1.1,5.1\n2 ON HSC,9000,0.7,-2\n"
    r = autoeq.parse_autoeq(text)
    assert len(r["filters"]) == 2
    assert r["filters"][1]["type"] == "highshelf"


def test_rew_parse_with_bandwidth():
    r = rew.parse_rew(REW_SAMPLE)
    assert len(r["filters"]) == 3
    bw_filter = r["filters"][1]
    assert bw_filter["type"] == "peak"
    # 1.5 oct -> Q ~= 0.956
    assert bw_filter["q"] == pytest.approx(0.92, abs=0.01)
    assert r["filters"][2]["type"] == "lowshelf"


def test_rew_bw_to_q_math():
    assert rew.bw_oct_to_q(1.0) == pytest.approx(1.41, abs=0.02)


def test_apo_parse():
    r = equalizerapo.parse_apo(APO_SAMPLE)
    assert r["preamp_db"] == -3.0
    assert r["devices"] == ["USB DAC XYZ"]
    pk = [f for f in r["filters"] if f["freq"] == 1000]
    assert pk and pk[0]["gain_db"] == -4.5
    geq = [f for f in r["filters"] if f["freq"] == 63]
    assert geq and geq[0]["gain_db"] == 2.1
    assert any("Include" in u for u in r["unknown"])


def test_graphiceq_q_from_spacing():
    filters = equalizerapo.graphic_eq_to_filters("100 3; 200 -3")
    assert len(filters) == 2
    assert filters[0]["q"] > 0.5


def test_csv_parse():
    r = detect.parse_csv(CSV_SAMPLE)
    assert len(r["filters"]) == 2
    assert r["filters"][0]["type"] == "peak"
    assert r["filters"][1]["type"] == "highshelf"


def test_detection(tmp_path):
    cases = {
        "autoeq.txt": (AUTOEQ_SAMPLE, "autoeq"),
        "rew.txt": (REW_SAMPLE, "rew"),
        "apo.txt": (APO_SAMPLE, "equalizerapo"),
        "table.csv": (CSV_SAMPLE, "csv"),
        "prof.json": ('{"format": "eqforge.profile", "format_version": 2,'
                      ' "id": "p", "eq": {"filters": []}}', "eqforge"),
    }
    for name, (text, fmt) in cases.items():
        p = tmp_path / name
        p.write_text(text)
        assert detect.detect_format(p) == fmt, name


def test_detect_and_import_creates_profile(tmp_path):
    p = tmp_path / "HD650.txt"
    p.write_text(AUTOEQ_SAMPLE)
    prof = detect.detect_and_import(p)
    assert prof.id == "imported.hd650"
    assert len(prof.filters) == 5
    assert prof.preamp_mode == "manual"
    assert prof.preamp_db == pytest.approx(-6.2)
    assert "autoeq" in prof.tags


def test_import_rejects_garbage(tmp_path):
    p = tmp_path / "junk.txt"
    p.write_text("hello world\nnothing to see\n")
    from eqforge.errors import ImportError_
    with pytest.raises(ImportError_):
        detect.detect_and_import(p)


def test_cli_import_roundtrip(tmp_path, isolated_home):
    """`eqforge import` then `eqforge show` on the imported profile."""
    from eqforge.cli.main import main
    src = tmp_path / "my-eq.txt"
    src.write_text(AUTOEQ_SAMPLE)
    rc = main(["import", str(src), "--id", "my-eq"])
    assert rc == 0
    rc = main(["validate", "my-eq"])
    assert rc == 0
    rc = main(["show", "my-eq", "--resolved"])
    assert rc == 0
